[package]
name = "playground"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "playground"
path = "main.rs"


[dependencies]
#> libs
xhstt = { workspace = true }
n_queens = { workspace = true }
n_queens_2 = { workspace = true }

#> remote
rand = { workspace = true }
rand_distr = { workspace = true }
rayon = { workspace = true }
# rerun = "0.13.0"
ndarray = { workspace = true }
itertools = { workspace = true }

plotters = "0.3.6"
plotters-backend = "0.3.6"
piston_window = "0.132.0"
systemstat = "0.2.3"
# plotters-piston = "0.3.0"

simple_moving_average = { workspace = true }

bitvec = { workspace = true }


[lints]
workspace = true
