################################################################################
[workspace]
resolver = "2"
members = [
    "bin/*",
    "lib/*",
]

# exclude = []
default-members = [ "bin/solver" ]


################################################################################
[workspace.dependencies]
#> lib
xhstt = { path = "lib/xhstt" }
alg_1 = { path = "lib/alg_1" }
alg_2 = { path = "lib/alg_2" }

#> remote
rand = { version = "0.8.5" }
hashbrown = "0.14.5"
indexmap = "2.2.6"
structstruck = "0.4.1"


################################################################################
# Clippy Configuration
[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
unwrap_used = "forbid"
expect_used = "forbid"

################################################################################
