################################################################################
[workspace]
resolver = "2"
members = [
    "bin/*",
    "lib/*",
]

# exclude = []
default-members = [ "bin/solver" ]


################################################################################
[workspace.dependencies]
#> lib
xhstt = { path = "lib/xhstt" }
alg_1 = { path = "lib/alg_1" }
alg_2 = { path = "lib/alg_2" }
alg_3 = { path = "lib/alg_3" }
alg_4 = { path = "lib/alg_4" }

#> remote
rand = { version = "0.8.5" }
rayon = "1.10.0"

ndarray = { version = "0.16.0", features = ["rayon"] }
ndarray_stats = { version = "0.5.1" }

hashbrown = "0.14.5"
indexmap = "2.2.6"
chrono = "0.4.38"

# xhstt
structstruck = "0.4.1"

# alg_4
genevo = "0.7"

# data log
rerun = "0.13.0"



################################################################################
# Clippy Configuration
[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
unwrap_used = "forbid"
expect_used = "forbid"

################################################################################
