################################################################################
[workspace]
resolver = "2"
members = [
    "bin/*",
    "lib/*",
]

# exclude = []
default-members = [ "bin/alg" ]


################################################################################
[workspace.dependencies]
#> lib
xhstt = { path = "lib/xhstt" }


################################################################################
# Clippy Configuration
[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
unwrap_used = "forbid"
expect_used = "forbid"

################################################################################
