[package]
name = "solver"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "solver"
path = "main.rs"

[dependencies]
#> libs <#
# alg_11 = { workspace = true }
alg_12 = { workspace = true }

xhstt = { workspace = true }

#> remote <#
rand = { workspace = true }
chrono = { workspace = true }

[lints]
workspace = true
