[package]
name = "solver"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "solver"
path = "main.rs"

[dependencies]
#> libs <#
xhstt = { workspace = true }
# alg_1 = { workspace = true }
# alg_2 = { workspace = true }
# alg_3 = { workspace = true }
# alg_4 = { workspace = true }
# alg_5 = { workspace = true }
# alg_6 = { workspace = true }
# alg_7 = { workspace = true }
# alg_8 = { workspace = true }
# alg_9 = { workspace = true }
# alg_10 = { workspace = true }
alg_11 = { workspace = true }

#> remote <#
rand = { workspace = true }

[lints]
workspace = true
