[package]
name = "auto_runner"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "auto_runner"
path = "main.rs"

[dependencies]
#> libs <#
ga = { workspace = true }
xhstt = { workspace = true }
alg_11 = { workspace = true }
alg_12 = { workspace = true }

#> remote <#
git2 = { workspace = true }
dotenvy = { workspace = true }
thiserror = { workspace = true }
csv = { workspace = true }
serde = { workspace = true }
pushover = { workspace = true }
ctrlc = { workspace = true }
chrono = { workspace = true }

[lints]
workspace = true
