[package]
name = "eggholder"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "eggholder"
path = "main.rs"

[dependencies]
#> libs <#

#> remote <#
rand = { workspace = true }
rand_distr = { workspace = true }
rayon = { workspace = true }
rerun = { workspace = true }

colors-transform = { workspace = true }

[lints]
workspace = true
