[package]
name = "alg"
version = "0.1.0"
edition = "2021"

[dependencies]
#> libs
xhstt = { workspace = true }

#> remote
serde = { version = "1.0.204", features = ["derive"] }
quick-xml = { version = "0.36.0", features = ["serialize"] }

[lints]
workspace = true
